-- ============================
-- Seed Dummy Data
-- ============================
-- This file is executed after migrations during `supabase db reset`
-- UUIDs are auto-generated by Supabase (gen_random_uuid())

DO $$
DECLARE
    -- User IDs
    v_admin_id UUID;
    v_user_id UUID;
    v_sato_id UUID;
    -- Base dates (last week's weekdays: Mon-Fri)
    -- Calculate last Monday: CURRENT_DATE - days_since_monday - 7
    -- DOW: Sunday=0, Monday=1, ..., Saturday=6
    -- days_since_monday = (DOW + 6) % 7
    v_last_monday DATE := CURRENT_DATE - ((EXTRACT(DOW FROM CURRENT_DATE)::int + 6) % 7 + 7);
    v_mon DATE;
    v_tue DATE;
    v_wed DATE;
    v_thu DATE;
    v_fri DATE;
    -- Attendance Record IDs
    v_ar_admin_1 UUID;
    v_ar_admin_2 UUID;
    v_ar_admin_3 UUID;
    v_ar_admin_4 UUID;
    v_ar_admin_5 UUID;
    v_ar_user_1 UUID;
    v_ar_user_2 UUID;
    v_ar_user_3 UUID;
    v_ar_user_4 UUID;
    v_ar_user_5 UUID;
    v_ar_sato_1 UUID;
    v_ar_sato_2 UUID;
    v_ar_sato_3 UUID;
    -- Work Session IDs
    v_ws_admin_1 UUID;
    v_ws_admin_2 UUID;
    v_ws_admin_3 UUID;
    v_ws_admin_4 UUID;
    v_ws_admin_5 UUID;
    v_ws_user_1 UUID;
    v_ws_user_2 UUID;
    v_ws_user_3 UUID;
    v_ws_user_4 UUID;
    v_ws_user_5 UUID;
    v_ws_sato_1 UUID;
    v_ws_sato_2 UUID;
    v_ws_sato_3 UUID;
    -- Daily Report IDs
    v_dr_admin_1 UUID;
    v_dr_admin_2 UUID;
    v_dr_admin_3 UUID;
    v_dr_user_1 UUID;
    v_dr_user_2 UUID;
    v_dr_sato_1 UUID;
    v_dr_sato_2 UUID;
BEGIN
    -- Initialize weekday dates (last week Mon-Fri)
    v_mon := v_last_monday;
    v_tue := v_last_monday + 1;
    v_wed := v_last_monday + 2;
    v_thu := v_last_monday + 3;
    v_fri := v_last_monday + 4;

    -- ============================
    -- Users
    -- Password: "password123" (bcrypt hash)
    -- ============================
    INSERT INTO public.users (name, email, employee_number, role, hashed_password)
    VALUES ('管理者', 'admin@example.com', 'EMP001', 'admin', '$2b$12$Qyu2VQHQ/tKOKJ.X/Je3DuUwizvPuDuqwh5qWOSsvNi0SbVS/VcdO')
    RETURNING id INTO v_admin_id;

    INSERT INTO public.users (name, email, employee_number, role, hashed_password)
    VALUES ('一般ユーザー', 'user@example.com', 'EMP002', 'user', '$2b$12$Qyu2VQHQ/tKOKJ.X/Je3DuUwizvPuDuqwh5qWOSsvNi0SbVS/VcdO')
    RETURNING id INTO v_user_id;

    INSERT INTO public.users (name, email, employee_number, role, hashed_password)
    VALUES ('佐藤 次郎', 'sato@example.com', 'EMP003', 'user', '$2b$12$Qyu2VQHQ/tKOKJ.X/Je3DuUwizvPuDuqwh5qWOSsvNi0SbVS/VcdO')
    RETURNING id INTO v_sato_id;

    -- ============================
    -- Attendance Records (last week Mon-Fri)
    -- ============================
    -- Admin (Mon-Fri)
    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_admin_id, v_mon)
    RETURNING id INTO v_ar_admin_1;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_admin_id, v_tue)
    RETURNING id INTO v_ar_admin_2;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_admin_id, v_wed)
    RETURNING id INTO v_ar_admin_3;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_admin_id, v_thu)
    RETURNING id INTO v_ar_admin_4;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_admin_id, v_fri)
    RETURNING id INTO v_ar_admin_5;

    -- Regular User (Mon-Fri)
    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_user_id, v_mon)
    RETURNING id INTO v_ar_user_1;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_user_id, v_tue)
    RETURNING id INTO v_ar_user_2;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_user_id, v_wed)
    RETURNING id INTO v_ar_user_3;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_user_id, v_thu)
    RETURNING id INTO v_ar_user_4;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_user_id, v_fri)
    RETURNING id INTO v_ar_user_5;

    -- Sato (Tue-Thu)
    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_sato_id, v_tue)
    RETURNING id INTO v_ar_sato_1;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_sato_id, v_wed)
    RETURNING id INTO v_ar_sato_2;

    INSERT INTO public.attendance_records (user_id, date)
    VALUES (v_sato_id, v_thu)
    RETURNING id INTO v_ar_sato_3;

    -- ============================
    -- Work Sessions
    -- Stored in UTC, displayed as JST on frontend
    -- Example: To display JST 09:00 -> store as UTC 00:00
    -- ============================
    -- Admin sessions (Mon-Fri)
    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_admin_1, v_mon + TIME '00:00:00', v_mon + TIME '09:00:00')
    RETURNING id INTO v_ws_admin_1;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_admin_2, v_tue + TIME '00:00:00' - INTERVAL '15 minutes', v_tue + TIME '08:30:00')
    RETURNING id INTO v_ws_admin_2;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_admin_3, v_wed + TIME '00:15:00', v_wed + TIME '10:00:00')
    RETURNING id INTO v_ws_admin_3;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_admin_4, v_thu + TIME '00:00:00', v_thu + TIME '09:30:00')
    RETURNING id INTO v_ws_admin_4;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_admin_5, v_fri + TIME '00:00:00' - INTERVAL '30 minutes', v_fri + TIME '08:00:00')
    RETURNING id INTO v_ws_admin_5;

    -- Regular user sessions (Mon-Fri)
    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_user_1, v_mon + TIME '01:00:00', v_mon + TIME '10:00:00')
    RETURNING id INTO v_ws_user_1;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_user_2, v_tue + TIME '00:30:00', v_tue + TIME '09:30:00')
    RETURNING id INTO v_ws_user_2;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_user_3, v_wed + TIME '00:00:00', v_wed + TIME '08:45:00')
    RETURNING id INTO v_ws_user_3;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_user_4, v_thu + TIME '01:15:00', v_thu + TIME '10:30:00')
    RETURNING id INTO v_ws_user_4;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_user_5, v_fri + TIME '00:00:00', v_fri + TIME '09:00:00')
    RETURNING id INTO v_ws_user_5;

    -- Sato sessions (Tue-Thu)
    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_sato_1, v_tue + TIME '00:00:00' - INTERVAL '1 hour', v_tue + TIME '07:30:00')
    RETURNING id INTO v_ws_sato_1;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_sato_2, v_wed + TIME '00:00:00', v_wed + TIME '09:00:00')
    RETURNING id INTO v_ws_sato_2;

    INSERT INTO public.work_sessions (attendance_id, clock_in, clock_out)
    VALUES (v_ar_sato_3, v_thu + TIME '00:00:00' - INTERVAL '15 minutes', v_thu + TIME '08:15:00')
    RETURNING id INTO v_ws_sato_3;

    -- ============================
    -- Breaks
    -- Stored in UTC, displayed as JST on frontend
    -- Example: To display JST 12:00 -> store as UTC 03:00
    -- ============================
    -- Admin breaks (Mon-Fri)
    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_admin_1, v_mon + TIME '03:00:00', v_mon + TIME '04:00:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_admin_2, v_tue + TIME '03:00:00', v_tue + TIME '04:00:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_admin_3, v_wed + TIME '03:30:00', v_wed + TIME '04:30:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_admin_4, v_thu + TIME '03:00:00', v_thu + TIME '04:00:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_admin_5, v_fri + TIME '03:00:00', v_fri + TIME '03:45:00');

    -- Regular user breaks (Mon-Fri)
    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_user_1, v_mon + TIME '04:00:00', v_mon + TIME '05:00:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_user_2, v_tue + TIME '03:30:00', v_tue + TIME '04:30:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_user_3, v_wed + TIME '03:00:00', v_wed + TIME '04:00:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_user_4, v_thu + TIME '04:00:00', v_thu + TIME '05:00:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_user_5, v_fri + TIME '03:00:00', v_fri + TIME '04:00:00');

    -- Sato breaks (Tue-Thu)
    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_sato_1, v_tue + TIME '03:00:00', v_tue + TIME '03:45:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_sato_2, v_wed + TIME '03:00:00', v_wed + TIME '04:00:00');

    INSERT INTO public.breaks (session_id, break_start, break_end)
    VALUES (v_ws_sato_3, v_thu + TIME '03:00:00', v_thu + TIME '03:30:00');

    -- ============================
    -- Daily Reports
    -- submitted_at is also stored in UTC
    -- ============================
    -- Admin reports (Mon, Tue, Wed)
    INSERT INTO public.daily_reports (user_id, date, summary, issues, notes, submitted_at)
    VALUES (v_admin_id, v_mon,
        'プロジェクトAの設計書レビューを完了。チームメンバーとの打ち合わせで方針を確定した。',
        'API仕様の一部が未確定のため、バックエンドチームとの調整が必要。',
        '明日は終日外出予定。',
        v_mon + TIME '09:00:00')
    RETURNING id INTO v_dr_admin_1;

    INSERT INTO public.daily_reports (user_id, date, summary, issues, notes, submitted_at)
    VALUES (v_admin_id, v_tue,
        'フロントエンド実装を開始。基本的なコンポーネント構成を作成した。',
        NULL,
        NULL,
        v_tue + TIME '08:30:00')
    RETURNING id INTO v_dr_admin_2;

    INSERT INTO public.daily_reports (user_id, date, summary, issues, notes, submitted_at)
    VALUES (v_admin_id, v_wed,
        'ユーザー認証機能の実装が完了。テストも通過した。',
        'パフォーマンスの最適化が今後の課題。',
        '週次ミーティングの議事録を共有フォルダにアップロード済み。',
        v_wed + TIME '10:00:00')
    RETURNING id INTO v_dr_admin_3;

    -- Regular user reports (Mon, Tue)
    INSERT INTO public.daily_reports (user_id, date, summary, issues, notes, submitted_at)
    VALUES (v_user_id, v_mon,
        'デザインシステムのドキュメント作成。コンポーネントライブラリの整理を実施。',
        'デザインツールのライセンス更新が必要。',
        NULL,
        v_mon + TIME '10:00:00')
    RETURNING id INTO v_dr_user_1;

    INSERT INTO public.daily_reports (user_id, date, summary, issues, notes, submitted_at)
    VALUES (v_user_id, v_tue,
        'UIコンポーネントのアクセシビリティ改善。スクリーンリーダー対応を追加。',
        NULL,
        '来週のデザインレビュー会議の準備中。',
        v_tue + TIME '09:30:00')
    RETURNING id INTO v_dr_user_2;

    -- Sato reports (Tue, Wed)
    INSERT INTO public.daily_reports (user_id, date, summary, issues, notes, submitted_at)
    VALUES (v_sato_id, v_tue,
        'データベース設計の見直し。インデックス最適化により検索速度が30%向上。',
        'テスト環境のディスク容量が不足気味。',
        NULL,
        v_tue + TIME '07:30:00')
    RETURNING id INTO v_dr_sato_1;

    INSERT INTO public.daily_reports (user_id, date, summary, issues, notes, submitted_at)
    VALUES (v_sato_id, v_wed,
        'API エンドポイントの追加実装。バリデーション処理を強化。',
        NULL,
        'コードレビューのフィードバックを反映済み。',
        NULL)
    RETURNING id INTO v_dr_sato_2;

    -- ============================
    -- Daily Report Tasks
    -- ============================
    -- Admin - 6 days ago
    INSERT INTO public.daily_report_tasks (daily_report_id, task_type, task_name, hours, sort_order) VALUES
        (v_dr_admin_1, 'planned', '設計書レビュー', 3.0, 1),
        (v_dr_admin_1, 'planned', 'チームミーティング', 2.0, 2),
        (v_dr_admin_1, 'actual', '設計書レビュー', 3.5, 1),
        (v_dr_admin_1, 'actual', 'チームミーティング', 2.0, 2),
        (v_dr_admin_1, 'actual', 'メール対応', 1.5, 3);

    -- Admin - 5 days ago
    INSERT INTO public.daily_report_tasks (daily_report_id, task_type, task_name, hours, sort_order) VALUES
        (v_dr_admin_2, 'planned', 'フロントエンド実装', 6.0, 1),
        (v_dr_admin_2, 'actual', 'フロントエンド実装', 5.5, 1),
        (v_dr_admin_2, 'actual', 'コードレビュー', 1.5, 2);

    -- Admin - 4 days ago
    INSERT INTO public.daily_report_tasks (daily_report_id, task_type, task_name, hours, sort_order) VALUES
        (v_dr_admin_3, 'planned', '認証機能実装', 5.0, 1),
        (v_dr_admin_3, 'planned', 'テスト作成', 3.0, 2),
        (v_dr_admin_3, 'actual', '認証機能実装', 5.5, 1),
        (v_dr_admin_3, 'actual', 'テスト作成', 2.5, 2),
        (v_dr_admin_3, 'actual', '週次ミーティング', 1.0, 3);

    -- Regular user - 6 days ago
    INSERT INTO public.daily_report_tasks (daily_report_id, task_type, task_name, hours, sort_order) VALUES
        (v_dr_user_1, 'planned', 'ドキュメント作成', 4.0, 1),
        (v_dr_user_1, 'planned', 'コンポーネント整理', 4.0, 2),
        (v_dr_user_1, 'actual', 'ドキュメント作成', 4.5, 1),
        (v_dr_user_1, 'actual', 'コンポーネント整理', 3.5, 2);

    -- Regular user - 5 days ago
    INSERT INTO public.daily_report_tasks (daily_report_id, task_type, task_name, hours, sort_order) VALUES
        (v_dr_user_2, 'planned', 'アクセシビリティ改善', 6.0, 1),
        (v_dr_user_2, 'actual', 'アクセシビリティ改善', 6.0, 1),
        (v_dr_user_2, 'actual', 'ミーティング準備', 1.0, 2);

    -- Sato - 5 days ago
    INSERT INTO public.daily_report_tasks (daily_report_id, task_type, task_name, hours, sort_order) VALUES
        (v_dr_sato_1, 'planned', 'DB設計見直し', 4.0, 1),
        (v_dr_sato_1, 'planned', 'インデックス最適化', 3.0, 2),
        (v_dr_sato_1, 'actual', 'DB設計見直し', 3.5, 1),
        (v_dr_sato_1, 'actual', 'インデックス最適化', 3.5, 2);

    -- Sato - 4 days ago
    INSERT INTO public.daily_report_tasks (daily_report_id, task_type, task_name, hours, sort_order) VALUES
        (v_dr_sato_2, 'planned', 'API実装', 5.0, 1),
        (v_dr_sato_2, 'planned', 'バリデーション追加', 2.0, 2),
        (v_dr_sato_2, 'actual', 'API実装', 5.0, 1),
        (v_dr_sato_2, 'actual', 'バリデーション追加', 2.0, 2),
        (v_dr_sato_2, 'actual', 'コードレビュー対応', 1.0, 3);

END $$;
